CC=gcc
CFLAGS=-Wall -Werror -g
SRCDIR=src
TESTDIR=tests
TEST_FLAGS=-I$(SRCDIR) -lcheck
LIBS=-lev -lsockutils -lbeanstalkproto -lioqueue
OBJECTS=beanstalkclient.o evvector.o

all:     libbeanstalkclient.so

check: $(TESTDIR)/ivector.t $(TESTDIR)/bsc.t
	$(TESTDIR)/ivector.t  
	$(TESTDIR)/bsc.t  

$(TESTDIR)/bsc.t: $(TESTDIR)/check_bsc.c evbsc.o
	$(CC) $(TEST_FLAGS) -o $(TESTDIR)/bsc.t $(TESTDIR)/check_bsc.c $(OBJECTS) $(LIBS)

$(TESTDIR)/ivector.t: $(TESTDIR)/check_ivector.c ivector.o
	$(CC) $(CFLAGS) $(TEST_FLAGS) -o $(TESTDIR)/ivector.t $(TESTDIR)/check_ivector.c ivector.o

libbeanstalkclient.so: $(OBJECTS)
	$(CC) $(CFLAGS) --shared -o libbeanstalkclient.so $(OBJECTS) $(LIBS)

ivector.o:    $(SRCDIR)/ivector.c
	$(CC) $(CFLAGS) -c $(SRCDIR)/ivector.c

beanstalkclient.o:    $(SRCDIR)/beanstalkclient.c
	$(CC) $(CFLAGS) -c $(SRCDIR)/beanstalkclient.c

clean:
	rm -f *.so *.o tests/*.t
